services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
  api:
    build: ./api
    env_file:
      - ./api/.env
    restart: always
    ports:
      - '${API_PORT:-3000}:3000'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - default

  listener:
    build: ./listener
    env_file:
      - ./listener/.env
    restart: always
    ports:
      - '${LISTENER_PORT:-3001}:3001'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        # TODO: Add healthcheck endpoint to api
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - default

networks:
  default:
