FROM node:18 as builder

WORKDIR /app

COPY package.json package-lock.json tsconfig.json tsconfig.build.json ./

RUN npm ci

COPY src/ ./src
COPY .env.example ./.env

# Keeping this here to run test transactions, not tests
COPY test/transaction.js ./test
COPY test/wallet.js ./test
RUN #node ./test/wallet.js

RUN npm run build

FROM node:18.12.1-slim as app

WORKDIR /app

COPY package.json package-lock.json ./
COPY .env.example ./.env

RUN npm ci --omit=dev

COPY --from=builder ./app/dist/ ./dist/

ENTRYPOINT ["node", "./dist/src/main.js"]
